'use client';
import {useState} from 'react';
import {Ticket,money,lbl} from './data';
export function Card({t,children}:any){return <section className="cartao"><h2>{t}</h2>{children}</section>}
export function I({t,v}:any){return <div className="indicador"><span>{t}</span><b>{v}</b></div>}
export function Bar({v}:{v:string}){let s=(v||'').replace(/[^A-Za-z0-9]/g,'').toUpperCase(),w=Math.max(260,s.length*12+28);return <svg viewBox={`0 0 ${w} 76`} className="barcode">{s.split('').map((c,i)=><rect key={i} x={14+i*12} y="8" width={c.charCodeAt(0)%4+2} height="44" fill="#111827"/>)}<text x={w/2} y="68" fontSize="10" textAnchor="middle">{s}</text></svg>}
export function TicketCard({t,d}:any){return <div className="ticket"><b>{t.item}</b><span>{t.code}</span>{t.qr&&<img src={t.qr} alt="QR Code"/>}<Bar v={t.token}/><strong>{money(t.v)}</strong><small>{t.token}</small><div className="ticket-actions">{d.channels?.whatsapp&&<button className="mini">WhatsApp</button>}{d.channels?.sms&&<button className="mini">SMS</button>}{d.channels?.email&&<button className="mini">E-mail</button>}</div>{!d.channels?.whatsapp&&!d.channels?.sms&&!d.channels?.email&&<p className="muted">Envio digital desativado pelo Super Admin.</p>}<button className="mini" onClick={()=>print()}>Imprimir</button></div>}
export function Login({d,login,msg}:any){let[e,setE]=useState('admin@example.test'),[p,setP]=useState('demo');let quick=[['Admin','admin@example.test'],['Caixa','caixa@example.test'],['Barraca','bebidas@example.test'],['Financeiro','financeiro@example.test']];return <main className="login"><section className="login-card"><div className="marca"><div className="marca-selo">{d.brand.sig}</div><div><b>{d.brand.name}</b><span>{d.brand.sub}</span></div></div><h1>Entrar no evento</h1><p className="muted">Operação de festival com caixa, barraca, financeiro e gestão.</p>{msg&&<div className="aviso erro">{msg}</div>}<label>E-mail/Login<input value={e} onChange={x=>setE(x.target.value)}/></label><label>Senha/PIN<input type="password" value={p} onChange={x=>setP(x.target.value)}/></label><button className="botao cheio" onClick={()=>login(e,p)}>Entrar</button><div className="atalhos">{quick.map(q=><button key={q[0]} onClick={()=>{setE(q[1]);setP('demo')}}>{q[0]}<span>{q[1]}</span></button>)}</div></section></main>}
export function Painel({d}:any){let sold=d.tickets.filter((t:Ticket)=>t.st!=='cancelado'),used=d.tickets.filter((t:Ticket)=>t.st==='consumido');return <><div className="indicadores"><I t="Vendas" v={money(sold.reduce((a:number,t:Ticket)=>a+t.v,0))}/><I t="Tickets" v={sold.length}/><I t="Consumidos" v={used.length}/><I t="Barracas" v={d.stalls.length}/></div><Card t="Estado"><p>Evento em modo <b>{d.mode==='produtos'?'Produtos por barraca':'Tickets por valor'}</b>. WhatsApp/SMS/E-mail só aparecem quando ativados em Gestão → Integrações.</p></Card></>}
export function Perfil({u,d,logout}:any){return <div className="grid-2"><Card t="Perfil"><b>{u.name}</b><p>{u.email}</p><p>{lbl(u.role)}</p><button className="botao cheio" onClick={logout}>Terminar sessão</button></Card><Card t="Estado"><b>{d.online?'Online':'Offline'}</b><p className="muted">No PWA, o logout fica aqui.</p></Card></div>}
