'use client';
import {useEffect,useState} from 'react';
type Data={online:boolean;event:any;events:any[];stalls:any[];products:any[];cashiers:any[]};
const empty:Data={online:false,event:null,events:[],stalls:[],products:[],cashiers:[]};
async function api(action:string,body:any={}){let r=await fetch('/api/symplex',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,...body})});let j=await r.json();if(!r.ok||j.ok===false)throw Error(j.error||j.message||'Erro no backend');return j}
const money=(v:number)=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
export default function Page(){const[d,setD]=useState<Data>(empty),[tab,setTab]=useState('events'),[msg,setMsg]=useState('A carregar...');async function load(){try{let j=await api('admin_list');setD({online:true,event:j.event,events:j.event?[j.event]:[],stalls:j.stalls||[],products:j.products||[],cashiers:j.cashiers||[]});setMsg('Online')}catch(e:any){setMsg('Offline ou erro: '+(e?.message||e))}}useEffect(()=>{load()},[]);return <main style={page}><header style={head}><div><h1 style={{margin:0}}>Gestão Admin Online</h1><p style={muted}>Frontend → Backend Vercel → Supabase</p><b style={{color:d.online?'#12805c':'#b42318'}}>{msg}</b></div><a href='/' style={light}>Voltar ao sistema</a></header><nav style={tabs}>{['events','stalls','products','cashiers'].map(x=><button key={x} onClick={()=>setTab(x)} style={tab===x?dark:light}>{lbl(x)}</button>)}</nav>{tab==='events'&&<Events d={d} load={load} setMsg={setMsg}/>} {tab==='stalls'&&<Stalls d={d} load={load} setMsg={setMsg}/>} {tab==='products'&&<Products d={d} load={load} setMsg={setMsg}/>} {tab==='cashiers'&&<Cashiers d={d} load={load} setMsg={setMsg}/>}</main>}
function Events({d,load,setMsg}:any){const[f,setF]=useState({id:'',name:'',location:'',sales_mode:'products'});async function ok(){try{await api('save_event',{data:f});setMsg('Evento guardado online.');setF({id:'',name:'',location:'',sales_mode:'products'});await load()}catch(e:any){setMsg('Erro: '+(e?.message||e))}}return <Grid><Card t='Evento'><Input p='Nome' v={f.name} c={(v:string)=>setF({...f,name:v})}/><Input p='Local' v={f.location} c={(v:string)=>setF({...f,location:v})}/><select style={field} value={f.sales_mode} onChange={e=>setF({...f,sales_mode:e.target.value})}><option value='products'>Produtos por barraca</option><option value='tickets'>Tickets por valor</option></select><button style={blue} onClick={ok}>Guardar no Supabase</button></Card><Card t='Eventos'>{d.events.map((x:any)=><Row key={x.id} a={x.name} b={`${x.location||''} · ${x.sales_mode||''}`} edit={()=>setF({id:x.id,name:x.name||'',location:x.location||'',sales_mode:x.sales_mode||'products'})}/>)}</Card></Grid>}
function Stalls({d,load,setMsg}:any){const[f,setF]=useState({id:'',name:'',owner:'',com:0,fix:0});async function ok(){try{await api('save_stall',{data:f});setMsg('Barraca guardada online.');setF({id:'',name:'',owner:'',com:0,fix:0});await load()}catch(e:any){setMsg('Erro: '+(e?.message||e))}}async function rem(id:string){try{await api('delete_admin',{table:'stalls',id});setMsg('Barraca desativada.');await load()}catch(e:any){setMsg('Erro: '+(e?.message||e))}}return <Grid><Card t='Barraca'><Input p='Nome' v={f.name} c={(v:string)=>setF({...f,name:v})}/><Input p='Responsável' v={f.owner} c={(v:string)=>setF({...f,owner:v})}/><Input p='Comissão %' type='number' v={String(f.com)} c={(v:string)=>setF({...f,com:Number(v)})}/><Input p='Taxa fixa' type='number' v={String(f.fix)} c={(v:string)=>setF({...f,fix:Number(v)})}/><button style={blue} onClick={ok}>Guardar no Supabase</button></Card><Card t='Barracas'>{d.stalls.map((x:any)=><Row key={x.id} a={x.name} b={`${x.commission_percent||0}% · ${money(x.fixed_fee||0)}`} edit={()=>setF({id:x.id,name:x.name||'',owner:x.owner_name||'',com:Number(x.commission_percent||0),fix:Number(x.fixed_fee||0)})} rem={()=>rem(x.id)}/>)}</Card></Grid>}
function Products({d,load,setMsg}:any){const[f,setF]=useState({id:'',name:'',price:0,stall:'todas'});async function ok(){try{await api('save_product',{data:f});setMsg('Produto/ticket guardado online.');setF({id:'',name:'',price:0,stall:'todas'});await load()}catch(e:any){setMsg('Erro: '+(e?.message||e))}}async function rem(id:string){try{await api('delete_admin',{table:'products',id});setMsg('Produto/ticket desativado.');await load()}catch(e:any){setMsg('Erro: '+(e?.message||e))}}return <Grid><Card t='Ticket ou produto'><Input p='Nome' v={f.name} c={(v:string)=>setF({...f,name:v})}/><Input p='Valor' type='number' v={String(f.price)} c={(v:string)=>setF({...f,price:Number(v)})}/><select style={field} value={f.stall} onChange={e=>setF({...f,stall:e.target.value})}><option value='todas'>Todas / ticket global</option>{d.stalls.map((b:any)=><option key={b.id} value={b.id}>{b.name}</option>)}</select><button style={blue} onClick={ok}>Guardar no Supabase</button></Card><Card t='Tickets e produtos'>{d.products.map((x:any)=><Row key={x.id} a={x.name} b={`${money(x.price)} · ${x.stall_id?'barraca':'global'}`} edit={()=>setF({id:x.id,name:x.name||'',price:Number(x.price||0),stall:x.stall_id||'todas'})} rem={()=>rem(x.id)}/>)}</Card></Grid>}
function Cashiers({d,load,setMsg}:any){const[f,setF]=useState({id:'',name:'',series:'A1',operator:''});async function ok(){try{await api('save_cashier',{data:f});setMsg('Caixa guardado online.');setF({id:'',name:'',series:'A1',operator:''});await load()}catch(e:any){setMsg('Erro: '+(e?.message||e))}}async function rem(id:string){try{await api('delete_admin',{table:'cashiers',id});setMsg('Caixa desativado.');await load()}catch(e:any){setMsg('Erro: '+(e?.message||e))}}return <Grid><Card t='Caixa / operador'><Input p='Nome do caixa' v={f.name} c={(v:string)=>setF({...f,name:v})}/><Input p='Série' v={f.series} c={(v:string)=>setF({...f,series:v})}/><Input p='Operador' v={f.operator} c={(v:string)=>setF({...f,operator:v})}/><button style={blue} onClick={ok}>Guardar no Supabase</button></Card><Card t='Caixas'>{d.cashiers.map((x:any)=><Row key={x.id} a={x.name} b={`${x.series} · ${x.operator_name||''}`} edit={()=>setF({id:x.id,name:x.name||'',series:x.series||'A1',operator:x.operator_name||''})} rem={()=>rem(x.id)}/>)}</Card></Grid>}
function Grid({children}:any){return <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(320px,1fr))',gap:16}}>{children}</div>}
function Card({t,children}:any){return <section style={card}><h2 style={{marginTop:0}}>{t}</h2>{children}</section>}
function Input({p,v,c,type='text'}:any){return <input placeholder={p} type={type} value={v} onChange={e=>c(e.target.value)} style={field}/>}
function Row({a,b,edit,rem}:any){return <div style={row}><div><b>{a}</b><small style={{display:'block',color:'#667085'}}>{b}</small></div><div><button onClick={edit} style={light}>Editar</button>{rem&&<button onClick={rem} style={warn}>Remover</button>}</div></div>}
function lbl(x:string){return({events:'Eventos',stalls:'Barracas',products:'Tickets/Produtos',cashiers:'Caixas'} as any)[x]||x}
const page={minHeight:'100vh',background:'#f6f7fb',padding:24,fontFamily:'Inter,system-ui,Arial'} as any,head={display:'flex',justifyContent:'space-between',gap:16,alignItems:'center',marginBottom:18} as any,tabs={display:'flex',gap:8,flexWrap:'wrap',marginBottom:18} as any,muted={color:'#667085'} as any,card={background:'#fff',border:'1px solid #e6e8ef',borderRadius:22,padding:18,boxShadow:'0 12px 28px rgba(16,24,40,.05)'} as any,field={width:'100%',border:'1px solid #e6e8ef',borderRadius:13,padding:12,margin:'7px 0 12px',font:'inherit'} as any,row={display:'flex',justifyContent:'space-between',gap:10,border:'1px solid #e6e8ef',borderRadius:14,padding:12,margin:'8px 0',background:'#fff'} as any,blue={border:0,background:'#2454d6',color:'#fff',borderRadius:14,padding:'12px 15px',fontWeight:900,cursor:'pointer'} as any,dark={border:'1px solid #111827',background:'#111827',color:'#fff',borderRadius:14,padding:'12px 15px',fontWeight:900,cursor:'pointer'} as any,light={border:'1px solid #e6e8ef',background:'#fff',color:'#223b8f',borderRadius:14,padding:'12px 15px',fontWeight:900,cursor:'pointer',textDecoration:'none',marginLeft:6} as any,warn={border:'1px solid #e6e8ef',background:'#fff',color:'#b42318',borderRadius:14,padding:'12px 15px',fontWeight:900,cursor:'pointer',marginLeft:6} as any;
