'use client';
import {useEffect,useState} from 'react';
type Data={events:any[];stalls:any[];items:any[];people:any[]};
const K='symplex-gestao-v1';
const seed:Data={events:[{id:'e1',nome:'Festival Demo',local:'Praca Central'}],stalls:[{id:'bebidas',nome:'Bebidas',comissao:12,fixo:0},{id:'pastel',nome:'Pastel',comissao:0,fixo:300}],items:[{id:'i1',nome:'Ticket R$ 10',tipo:'ticket',valor:10,barraca:'todas'},{id:'i2',nome:'Cerveja 600 ml',tipo:'produto',valor:15,barraca:'bebidas'}],people:[{id:'p1',nome:'Caixa',email:'caixa@demo.com',perfil:'caixa'},{id:'p2',nome:'Bebidas',email:'bebidas@demo.com',perfil:'barraca',barraca:'bebidas'}]};
const uid=(p:string)=>p+Math.random().toString(36).slice(2,8),money=(v:number)=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
export default function Page(){const[d,setD]=useState<Data>(seed),[tab,setTab]=useState('events');useEffect(()=>{try{setD(JSON.parse(localStorage.getItem(K)||'')||seed)}catch{}},[]);function save(n:Data){setD(n);localStorage.setItem(K,JSON.stringify(n))}return <main style={page}><header style={head}><div><h1 style={{margin:0}}>Gestao Desktop</h1><p style={muted}>Eventos, barracas, tickets/produtos e utilizadores.</p></div><a href='/' style={light}>Voltar</a></header><nav style={tabs}>{['events','stalls','items','people'].map(x=><button key={x} onClick={()=>setTab(x)} style={tab===x?dark:light}>{lbl(x)}</button>)}</nav>{tab==='events'&&<Events d={d} save={save}/>} {tab==='stalls'&&<Stalls d={d} save={save}/>} {tab==='items'&&<Items d={d} save={save}/>} {tab==='people'&&<People d={d} save={save}/>}</main>}
function Events({d,save}:any){const[f,setF]=useState({id:'',nome:'',local:''});function ok(){let r={...f,id:f.id||uid('e')};save({...d,events:[r,...d.events.filter((x:any)=>x.id!==r.id)]});setF({id:'',nome:'',local:''})}return <Grid><Card t='Evento'><Inp p='Nome' v={f.nome} c={(v:string)=>setF({...f,nome:v})}/><Inp p='Local' v={f.local} c={(v:string)=>setF({...f,local:v})}/><button style={blue} onClick={ok}>Guardar</button></Card><Card t='Eventos'>{d.events.map((x:any)=><Row key={x.id} a={x.nome} b={x.local} edit={()=>setF(x)} rem={()=>save({...d,events:d.events.filter((y:any)=>y.id!==x.id)})}/>)}</Card></Grid>}
function Stalls({d,save}:any){const[f,setF]=useState({id:'',nome:'',comissao:0,fixo:0});function ok(){let r={...f,id:f.id||uid('b')};save({...d,stalls:[r,...d.stalls.filter((x:any)=>x.id!==r.id)]});setF({id:'',nome:'',comissao:0,fixo:0})}return <Grid><Card t='Barraca'><Inp p='Nome' v={f.nome} c={(v:string)=>setF({...f,nome:v})}/><Inp p='Comissao %' type='number' v={String(f.comissao)} c={(v:string)=>setF({...f,comissao:Number(v)})}/><Inp p='Taxa fixa' type='number' v={String(f.fixo)} c={(v:string)=>setF({...f,fixo:Number(v)})}/><button style={blue} onClick={ok}>Guardar</button></Card><Card t='Barracas'>{d.stalls.map((x:any)=><Row key={x.id} a={x.nome} b={`${x.comissao}% | ${money(x.fixo)}`} edit={()=>setF(x)} rem={()=>save({...d,stalls:d.stalls.filter((y:any)=>y.id!==x.id)})}/>)}</Card></Grid>}
function Items({d,save}:any){const[f,setF]=useState({id:'',nome:'',tipo:'produto',valor:0,barraca:'todas'});function ok(){let r={...f,id:f.id||uid('i')};save({...d,items:[r,...d.items.filter((x:any)=>x.id!==r.id)]});setF({id:'',nome:'',tipo:'produto',valor:0,barraca:'todas'})}return <Grid><Card t='Ticket ou produto'><Inp p='Nome' v={f.nome} c={(v:string)=>setF({...f,nome:v})}/><select style={field} value={f.tipo} onChange={e=>setF({...f,tipo:e.target.value})}><option value='ticket'>Ticket</option><option value='produto'>Produto</option></select><Inp p='Valor' type='number' v={String(f.valor)} c={(v:string)=>setF({...f,valor:Number(v)})}/><select style={field} value={f.barraca} onChange={e=>setF({...f,barraca:e.target.value})}><option value='todas'>Todas</option>{d.stalls.map((b:any)=><option key={b.id} value={b.id}>{b.nome}</option>)}</select><button style={blue} onClick={ok}>Guardar</button></Card><Card t='Itens'>{d.items.map((x:any)=><Row key={x.id} a={x.nome} b={`${x.tipo} | ${money(x.valor)}`} edit={()=>setF(x)} rem={()=>save({...d,items:d.items.filter((y:any)=>y.id!==x.id)})}/>)}</Card></Grid>}
function People({d,save}:any){const[f,setF]=useState({id:'',nome:'',email:'',perfil:'caixa',barraca:''});function ok(){let r={...f,id:f.id||uid('p')};save({...d,people:[r,...d.people.filter((x:any)=>x.id!==r.id)]});setF({id:'',nome:'',email:'',perfil:'caixa',barraca:''})}return <Grid><Card t='Utilizador'><Inp p='Nome' v={f.nome} c={(v:string)=>setF({...f,nome:v})}/><Inp p='Email' v={f.email} c={(v:string)=>setF({...f,email:v})}/><select style={field} value={f.perfil} onChange={e=>setF({...f,perfil:e.target.value})}><option>financeiro</option><option>caixa</option><option>barraca</option></select><select style={field} value={f.barraca} onChange={e=>setF({...f,barraca:e.target.value})}><option value=''>Sem barraca</option>{d.stalls.map((b:any)=><option key={b.id} value={b.id}>{b.nome}</option>)}</select><button style={blue} onClick={ok}>Guardar</button></Card><Card t='Utilizadores'>{d.people.map((x:any)=><Row key={x.id} a={x.nome} b={`${x.email} | ${x.perfil}`} edit={()=>setF(x)} rem={()=>save({...d,people:d.people.filter((y:any)=>y.id!==x.id)})}/>)}</Card></Grid>}
function Grid({children}:any){return <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(320px,1fr))',gap:16}}>{children}</div>}
function Card({t,children}:any){return <section style={card}><h2 style={{marginTop:0}}>{t}</h2>{children}</section>}
function Inp({p,v,c,type='text'}:any){return <input placeholder={p} type={type} value={v} onChange={e=>c(e.target.value)} style={field}/>}
function Row({a,b,edit,rem}:any){return <div style={row}><div><b>{a}</b><small style={{display:'block',color:'#667085'}}>{b}</small></div><div><button onClick={edit} style={light}>Editar</button> <button onClick={rem} style={warn}>Remover</button></div></div>}
function lbl(x:string){return({events:'Eventos',stalls:'Barracas',items:'Tickets/Produtos',people:'Utilizadores'} as any)[x]||x}
const page={minHeight:'100vh',background:'#f6f7fb',padding:24,fontFamily:'Inter,system-ui,Arial'} as any,head={display:'flex',justifyContent:'space-between',gap:16,alignItems:'center',marginBottom:18} as any,tabs={display:'flex',gap:8,flexWrap:'wrap',marginBottom:18} as any,muted={color:'#667085'} as any,card={background:'#fff',border:'1px solid #e6e8ef',borderRadius:22,padding:18,boxShadow:'0 12px 28px rgba(16,24,40,.05)'} as any,field={width:'100%',border:'1px solid #e6e8ef',borderRadius:13,padding:12,margin:'7px 0 12px',font:'inherit'} as any,row={display:'flex',justifyContent:'space-between',gap:10,border:'1px solid #e6e8ef',borderRadius:14,padding:12,margin:'8px 0',background:'#fff'} as any,blue={border:0,background:'#2454d6',color:'#fff',borderRadius:14,padding:'12px 15px',fontWeight:900,cursor:'pointer'} as any,dark={border:'1px solid #111827',background:'#111827',color:'#fff',borderRadius:14,padding:'12px 15px',fontWeight:900,cursor:'pointer'} as any,light={border:'1px solid #e6e8ef',background:'#fff',color:'#223b8f',borderRadius:14,padding:'12px 15px',fontWeight:900,cursor:'pointer',textDecoration:'none'} as any,warn={border:'1px solid #e6e8ef',background:'#fff',color:'#b42318',borderRadius:14,padding:'12px 15px',fontWeight:900,cursor:'pointer'} as any;
